---
title: "AME_PS"
author: "Kristin, Genevieve, and Roshni"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

```{r}
ocean_data <- read_csv(here("data", "Data.csv"))
```

```{r}
mean_density_adult <- ocean_data[6:18, ] %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  select(!c(na_2, na_3, na_4, na_5)) %>% 
  rename(organism = na) %>% 
  drop_na() %>% 
  rename(CI = each_sampling_date) %>% 
  mutate(organism = case_when(
    organism == "Surgeonfish (herbivores)" ~ "Surgeonfish",
    organism == "Coral Trout (predators of adult fishes)" ~ "Coral Trout",
    organism == "Spotted Damselfish (eats zooplankton)" ~ "Spotted Damselfish",
    organism == "Yellow Damselfish (eats zooplankton)" ~ "Yellow Damselfish",
    TRUE ~ organism
  ))

adult_2006 <- mean_density_adult %>% 
  select(organism, rarotonga, aitutaki, CI) %>% 
  mutate(CI = as.numeric(CI)) %>% 
  rename(Rarotonga = rarotonga) %>% 
  rename(Aitutaki = aitutaki) %>% 
  mutate(Rarotonga = as.numeric(Rarotonga)) %>% 
  mutate(Aitutaki = as.numeric(Aitutaki)) %>% 
  mutate(year = 2006)

adult_2022 <- mean_density_adult %>% 
  select(organism, rarotonga_2, aitutaki_2, CI) %>% 
  mutate(CI = as.numeric(CI)) %>% 
  rename(Rarotonga = rarotonga_2) %>% 
  rename(Aitutaki = aitutaki_2) %>% 
  mutate(Rarotonga = as.numeric(Rarotonga)) %>% 
  mutate(Aitutaki = as.numeric(Aitutaki)) %>% 
  mutate(year = 2022)

adult <- rbind(adult_2006, adult_2022)
```

```{r}
mean_number_new_young <- ocean_data[28:52, ] %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  select(!c(na_3, na_4, na_5)) %>% 
  rename(microhabitat = na_2) %>% 
  rename(fish = na) %>% 
  rename(CI = each_sampling_date) %>% 
  mutate(fish = row_number()) %>% 
  drop_na() %>% 
  mutate(fish = case_when(
    fish == c(2,3,4,5,6) ~ "Surgeonfish",
    fish == c(8,9,10,11,12) ~ "Coral Trout",
    fish == c(14,15,16,17,18) ~ "Spotted Damselfish",
    fish == c(20,21,22,23,24) ~ "Yellow Damselfish"
  ))

young_2006 <- mean_number_new_young %>% 
  select(fish, microhabitat, rarotonga, aitutaki, CI)

young_2022 <- mean_number_new_young %>% 
  select(fish, microhabitat, rarotonga_2, aitutaki_2, CI) %>% 
  rename(Rarotonga = rarotonga_2) %>% 
  rename(Aitutaki = aitutaki_2)
```

Question 1
```{r}
# Rarotonga histograms

adult_ci <- adult %>% 
  pivot_longer(cols = c(Rarotonga, Aitutaki), names_to = "location", values_to = "mean_density") %>% 
  mutate(ci_low = mean_density - CI) %>% 
  mutate(ci_high = mean_density + CI)

surgeonfish_adult <- adult_ci %>% 
  filter(organism == "Surgeonfish")

coral_trout_adult <- adult_ci %>% 
  filter(organism == "Coral Trout")

spotted_damselfish_adult <- adult_ci %>% 
  filter(organism == "Spotted Damselfish")

yellow_damselfish_adult <- adult_ci %>% 
  filter(organism == "Yellow Damselfish")

mounding_corals_adult <- adult_ci %>% 
  filter(organism == "Mounding Corals")

corase_corals_adult <- adult_ci %>% 
  filter(organism == "Coarse-branching Corals")

fine_corals_adult <- adult_ci %>% 
  filter(organism == "Fine-branching Corals")

sea_anemones_adult <- adult_ci %>% 
  filter(organism == "Sea Anemones")

algae_adult <- adult_ci %>% 
  filter(organism == "Algae")

# Sugeonfish
ggplot(data = surgeonfish_adult)+
  geom_col(aes(x = location, y = mean_density, fill = location))+
  facet_wrap(~year) +
  theme_minimal() +
  theme(legend.position ="none") +
  labs(x = "Location", y = "Mean Density of Surgeonfish") +
  geom_errorbar(aes(x = location, y = mean_density, ymin = ci_low, ymax = ci_high), width = 0.2)
```

Question 2
```{r}

```

